### ISSUE TITLE
Setup script config file

### ISSUE THREAD

**Issue by JamshedVesuna** [altoduo/dotfiles#23]
Have a config file for features. Example:

Spotifybash: True

This would make the setup scrip enable sourcing of the spotifybash file, but if set to false, would not.
@DepthDeluxe thoughts? Let's expand on what to toggle.

Possible others:
* colorschemes (terminator, vim, etc)
* .rc files (whether to use bashrc, vimrc, etc)

**Comment by JamshedVesuna** [comment]
@DepthDeluxe want to just do this in puppet to close this out? Seems like its fitting for good ol puppet

**Comment by DepthDeluxe** [comment]
@JamshedVesuna yes, this sounds good.  Will be doing #62 instead of this.
