### ISSUE TITLE
cTags support for vim

### ISSUE THREAD

**Issue by JamshedVesuna** [altoduo/dotfiles#31]
include a ~/.ctags file. Take a look at http://andrew.stwrt.ca/posts/vim-ctags

**Comment by JamshedVesuna** [comment]
@DepthDeluxe Look at the bottom of [this](http://andrew.stwrt.ca/posts/vim-ctags) with `~/.ctags`. Interested in building a config file for this? If not, we can just close this out.

**Comment by DepthDeluxe** [comment]
I don't think we need to configure it. At least for right now.
