### ISSUE TITLE
Goto() allow priority folders

### ISSUE THREAD

**Issue by DepthDeluxe** [altoduo/dotfiles#44]
It would be nice to be include a list of priority folders that `goto()` looks into first before looking at the rest of the folder structure.  I find my main use case is to go somewhere into `college/fall14` directory.  This could be implemented in a `.gotopriority` file in the user's root directory.  In addition there could be a basic CLI implemented so the user doesn't have to mess around with that file.

@JamshedVesuna  what do you think?

**Comment by JamshedVesuna** [comment]
I don't really use goto() anymore just fyi

**Comment by DepthDeluxe** [comment]
not really needed anymore.  Original problems stemmed from the implementation being a bit buggy
