### ISSUE TITLE
Add puppet setup file

### ISSUE THREAD

**Issue by JamshedVesuna** [altoduo/dotfiles#62]
Just another easy way of setting stuff up. Would look similar to `setup.sh` but cleaner.

**Comment by DepthDeluxe** [comment]
related to #23

**Comment by DepthDeluxe** [comment]
for this, do we want a puppet file that does the base install of this repo?

**Comment by JamshedVesuna** [comment]
@DepthDeluxe Basically. It would be really nice to have a full puppet file that sets things up like how the setup file does. 
Just for clarity, I meant that puppet does the heavy lifting instead of just calling the setup file (as this file is pretty convoluted)

**Comment by DepthDeluxe** [comment]
Kk +1
