### ISSUE TITLE
Zsh Directory Colors

### ISSUE THREAD

**Issue by JamshedVesuna** [altoduo/dotfiles#65]

**Comment by DepthDeluxe** [comment]
Not having this problem anymore with imported `.zshrc`.

**Comment by JamshedVesuna** [comment]
@DepthDeluxe Do you see color differences between different kinds of files? Would you want this?

**Comment by DepthDeluxe** [comment]
I see differences between folders, files, and symlinks if that's what you
mean.

**Comment by JamshedVesuna** [comment]
Ah yes good enough.
