### ISSUE TITLE
Dropbox Public Url in functions

### ISSUE THREAD

**Issue by JamshedVesuna** [altoduo/dotfiles#68]
The Dropbox cli is linux specific and doesn't work on all systems. While I do think linux should be the backbone of dotfiles, Their Python and Ruby (and more) SDK is universal.

@DepthDeluxe are you okay if I switch the `puburl()` function in `bash/functions.sh` to use the Ruby SDK instead?

**Comment by DepthDeluxe** [comment]
Its def a better idea to have universal support over keeping it simple with
BASH.
