### ISSUE TITLE
Vim autochir?

### ISSUE THREAD

**Issue by JamshedVesuna** [altoduo/dotfiles#73]
@DepthDeluxe right now, the set directory of vim is where it was called from as opposed to where the file is located. Which do you think is better? Both have their pros and cons. Might be worth going through this.
Not a huge deal though

Can be set by `set autochdir`

**Comment by DepthDeluxe** [comment]
@JamshedVesuna not really sure if one is more useful than the other.  Having a statically positioned `vim` instance will make it easier to do things like run `make` and `ctags` but may be a little confusing when building Latex files.  Maybe we should just leave this up to the user's own custom files...

**Comment by JamshedVesuna** [comment]
Good point about make and such. I was actually having the reverse problem. Because I use NERDTree, I have to manually CD into a dir. Otherwise things like `make` and such fail. But I agree, this should be up to the personal user. Better yet, I could add this to my mac vim rc file.
