### ISSUE TITLE
Vim O delay

### ISSUE THREAD

**Issue by JamshedVesuna** [altoduo/dotfiles#74]
Vim is waiting for another keystroke on capital O.

**Comment by JamshedVesuna** [comment]
@DepthDeluxe Do you see this? It may have just been a product of ssh delay.

**Comment by DepthDeluxe** [comment]
@JamshedVesuna no i don't, something else happens when you press `<Ctrl-O>` but I don't think you mean that...

**Comment by JamshedVesuna** [comment]
* Capital O, not Ctrl O. Can you check this? On my laptop I see no delay, but try sshing into something and try that. Vim defaults in normal mode makes capital O go into insert mode and adds a line above.

**Comment by DepthDeluxe** [comment]
What mode (normal or insert) do you find the delay happening on?

**Comment by JamshedVesuna** [comment]
When in normal mode, pressing shift o does as I described above. I think a plugin or something else may use the beginning of this as a hotkey causing they delay.

**Comment by JamshedVesuna** [comment]
It's this problem: http://stackoverflow.com/questions/2158516/delay-before-o-opens-a-new-line

**Comment by JamshedVesuna** [comment]
Fixed with this: https://code.google.com/p/vim/issues/detail?id=24
