### ISSUE TITLE
ZSH implicitly opens vim

### ISSUE THREAD

**Issue by DepthDeluxe** [altoduo/dotfiles#75]
when you type a file into zsh it tries to open the file in Vim.  This can be rather annoying if you accidentally type something like `$(ls)` as it opens all files in a folder in Vim.  Would be nice if this feature wasn't there.

**Comment by DepthDeluxe** [comment]
@JamshedVesuna

**Comment by JamshedVesuna** [comment]
I had this as a feature because I used it for a while, but I see where it would be a bad idea. Reverted.
