### ISSUE TITLE
ZSH tab completion changes text color

### ISSUE THREAD

**Issue by DepthDeluxe** [altoduo/dotfiles#76]
@JamshedVesuna, when I tab-complete, in ZSH it changes the line color which messes with the color of program output and etc...

**Comment by JamshedVesuna** [comment]
Screenshot would be helpful here. I'm not having this issue.

**Comment by DepthDeluxe** [comment]
![screenshot from 2015-03-03 16 38 46](https://cloud.githubusercontent.com/assets/4984331/6472933/cedfb210-c1c3-11e4-935c-7e018b9f535b.png)

**Comment by DepthDeluxe** [comment]
screenshot application defocuses current window but on my machine, the really black text looks white after hitting tab twice.

**Comment by JamshedVesuna** [comment]
Is this still true after the latest commit?

**Comment by DepthDeluxe** [comment]
ahh awesome!  It's resolved.
