### ISSUE TITLE
Manpages no longer colored

### ISSUE THREAD

**Issue by DepthDeluxe** [altoduo/dotfiles#78]
@JamshedVesuna what happened to this marvelous thing?!

**Comment by JamshedVesuna** [comment]
I took this out, it never really worked for me, especially with search highlighting. I'd be happy to include it in zshrc

**Comment by DepthDeluxe** [comment]
Yeah it would actually be kinda nice to have this. I'll see if I can add it
back.

**Comment by JamshedVesuna** [comment]
Lol I added it with b3b7318a202bae6e4a31d140035ff201090f9094
