### ISSUE TITLE
Regain vim's semicolon functionality

### ISSUE THREAD

**Issue by JamshedVesuna** [altoduo/dotfiles#80]
We currently have `nnoremap ; :`.  However, just like the `.` command (which repeats the last insertion command), `;` repeats the last general command (namely, in normal mode). This is extremely useful in many cases (where the bracket is where your cursor is. One simple example:

Running the command `fa`, instead of doing this over and over, its much faster to just `fa;;;(etc.)`.
`[T]his is a really long sentence with many apples and letter a's in it`

Of course, vim's easy-motion kind of takes care of this, but it would be awesome to regain `;`'s functionality back. One thought is to just map some `<leader>` command, but this negates the simple single key press repeat.
We've been trained to use semicolon in the place of colon for a while now, but I wanted to brainstorm this. Thoughts @DepthDeluxe?

**Comment by JamshedVesuna** [comment]
Relate to https://github.com/altoduo/dotfiles/pull/83

**Comment by JamshedVesuna** [comment]
Closed by #83

**Comment by DepthDeluxe** [comment]
@JamshedVesuna we didn't revert the mapping right?  Just thought I'd check.

**Comment by JamshedVesuna** [comment]
Nope, it's merged in [here](https://github.com/altoduo/dotfiles/blob/master/vim/.vimrc#L15)
