### ISSUE TITLE
Essay Mode?

### ISSUE THREAD

**Issue by JamshedVesuna** [altoduo/dotfiles#81]
I find myself writing too many essays in vim. @DepthDeluxe would you be opposed to having an essay mode (callable by a function) that sets things like text width, modeling with word count, etc?

Features:

- [x] set spell
- [ ] autocorrect to first suggestion (ability to toggle this)
- [x] set text width = 80
- [ ] define file type (txt, markdown, etc)
- [ ] caseless autocompletion
- [ ] grammar checking (does a sentence make sense?)
- [ ] if markdown, have macros to auto-header lines? (debatable)
- [x] modeline with word count and pages

**Comment by DepthDeluxe** [comment]
No thats fine. Maybe map to another function key or something. Don't make
it mapped to a ctl-letter though. Maybe <Leader-e>.

You could also make it a separate vim plugin as well.

**Comment by JamshedVesuna** [comment]
Features:

- [ ] set spell
- [ ] autocorrect to first suggestion (ability to toggle this)
- [ ] set text width = 80
- [ ] define file type (txt, markdown, etc)

**Comment by JamshedVesuna** [comment]
Possible extensions of this plugin:
