### ISSUE TITLE
Key Exchange

### ISSUE THREAD

**Issue by JamshedVesuna** [altoduo/dotfiles#89]
Add simple script to exchange public ssh keys for passwordless ssh (it's annoying to do this manually each time)

**Comment by DepthDeluxe** [comment]
Scp ~/.ssh/authorized_keys user@remote:~/.ssh

**Comment by JamshedVesuna** [comment]
Huh? You don't want to move your authorized keys to the remote... Just add your pub key to the remote's auth keys....

`cat ~/.ssh/id_rsa.pub | ssh user@remote 'cat >> .ssh/authorized_keys'`

This is annoying because you have to append your key to the end of their auth keys file. A simple alias would help :smile:

**Comment by JamshedVesuna** [comment]
Closed by 40aa6026e50e3114a6d1383cc8eb971270b2fff6
